### ISSUE TITLE
react-native/no-unused-style no working

### ISSUE THREAD

**Issue by Mokto** [gabbes/eslint-config-react-native-typescript#5]
Hi,

I don't get any alert about that rule. 

Thanks!

**Comment by gabts** [comment]
Hi, thank you for reporting this. 

What version of React Native are you using? 

Seems to works fine on my current project but noticed it doesn't work on a new project running React Native 0.62. Will investigate.

**Comment by gabts** [comment]
Hello,

Thank you for reporting this. I have released a fix in version 2.0.1.

Please keep in mind that I have released a new major version recently and a few other things might have changed depending on your current version.

The issue seemed to related to eslint-plugin-prettier not being installed correctly.

If you don't want to upgrade your existing version of eslint-config-react-native-typescript please try to add eslint-plugin-prettier as a dependency in your own project.

Please reopen this issue if none of the above solved this issue for you. Thanks again!
